### ISSUE TITLE
How to get products from trash?

### ISSUE THREAD

**Issue by dmaslov** [kloon/WooCommerce-REST-API-Client-Library#7]
Hi!
I need to get products which `post_status` = trash. Those products are not permanently deleted. Do i need to use a filter to get those products, or it's impossible to get it?
Thanks for answer in advance

**Comment by wywarren** [comment]
For anyone that is stumbling on this thread with the same needs, it's still currently not accessible with woocommerce rest api, however if you use wordpress rest api with /product/?post_type=product&status=trash you can get the same results.

Alternatively, you could also do the same with updating the product statuses as such. I remember doing this a while ago and forgot how I did it and recently a coworker asked for the same feature and I ended up finding my workaround in my old code.

Hope this helps others since this is the one of the highest ranked google searches on the topic.
